travis:
  secure:
    BINSTAR_TOKEN: H0Y6H6+iEpuwg2lv/vpXPoCh8WdBvGdkToPdc2jMtr+7dKTjANCX3yw/6A1DnzIvXIszLZs+cx0AXZl3EGIvYISsbTDv1ZD0ymoeEJ3JTjDVqraEH9s9Zs7YMG6eOlOlv/nW2pGE/tiHn9shAIZF97sGYDkQ7aQIeSznMfcm7arKZRgXTk21T3N2ouEkcNMFRfCcet58OrrnxqmaUTdXo+4HWTx+AYuiVKnxwdYx21cKQOZpw6PPcCsU0YNMFLi10BKh4wyrFzrBdNGmpMXFbnQH3OmOuCb/hQXMufUxay00WtdKu6/hcyqLeVxzKnB6K+rpchkd8IFiADdghAsKTNdUsw61x6JU4A4/sxR5wEjKjtIdF7LYBsDFkAS/f0DuSvsOOIByp+XKRdeZzBY1ONwvrrOk0KLu7mtMPDr9o/f6th/ZVBmR/SlhLsdt1bzXdHWvEIVrfNDT1crwcXD0aheBYKPkrVNPj5nksOyO/geRRk5xzjsSPqzRQPa7mozVCLFMTA/VpSDaYVkgNSo4JQh9VVkB1b94+zUyfjG4nul8rf8nmMKmJ6AMPRKNFkDFNfINyVi+BIwT7Ww/jfep5DZvKY2JrH4ha8x4RS3jSHDhNicZr7q/ZtnL1eBkyb/lg5er1ZFmyI1q04DHH/YZkO2eMIxQTaz6TdeuYMkuGbo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
