travis:
  secure:
    BINSTAR_TOKEN: MIftvbzfAUrPopEWs/sg0tUKaogYJZ8w0yDwTq66gye5wxZGslf98aM2PE/qoe+npAXn8KnMLdeOMgAv7NlXvGdY+fjYYbk7EAT04WhcTBubE9v9wKVY38PTE2H0Q44nNRCY0dw2zl3QXm9XwFz2Gx0Yvls243b7k1u9dIPKUoP2xYFv0lAcC/sIDabAvhiZC22PvB0onNTyUT1ZfSdHlFkS4Oej/uQqOzU5ml6yAircujB+9+A5HOsWNKzjMh+pxuMK5N0qwjCXvOXbsbgtvfYa0ztJxLKL7mHz2RSg3Jd4Myz+SS1f7AL5r6SCLHXxvqIolAHuMczapqlGo6U4NZxL921D6tqW22oOZcEM/N9KRvU431X5/+izriS/mxsmt58jSzk9pPhOUlvC/yqnw9d5oooYwLNydRxV1rCtBlsM1A6MVjDjZ2rLibfmkanLAvyWY9fb291k+PYn5mMEk86ZSKDbNoO8n9pQpFqAhErKOSEwxXUGgOr6mx2UQ4JoUnhQ7T4FAQ/9SwVKVaQlH0A/UtdODWAGzWwhnkcgC5bqFKFI+hxCAWF7nD/1HKAURnFhxDAmxnGc5fHY4usjFnuwcZGbfc4AlOLX4uFU3rUEEyHzQhLFZuxsFpkYoFwxfNy1H/4lDrLSqhALBWfNEJ1eX8VmqtxAKbPOtDK61Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
